### PR TITLE
UI_fixes

### PR DESCRIPTION
**Pull request by RikKargones**
Hello!
Just wonna contribute a bit.

List of changes:
1. Aded more UI scales to support not so big screen sizes: Supersmall (0.5) and Small (0.75). Also aded Superlarge (1.5). Normal now is under 3 in settings. Font in Supersmall scale can be blurry in some places.

2. Aded ScrollContainer as root in "Main" scene to save unlucky souls what sets too big UI scale on small screens.

3. Fixed resizing issues after UI scale change.

4. Changed how menu handled a bit for more save usage - using a TabContainer istead of PanelContainer and individual button signal connections to navigation.

5. Aded "exit_app()" func to Controller singleton trying to fix harmless crash on app exit (failed). I think it can be good place to make exit preporations in the future.

### CODE REVIEW

**Comment by YuriSizov** [comment]
Hey, thanks for deciding to contribute! As a general rule I would ask that you submit multiple PRs for unrelated changes/fixes. This makes it easier to discuss each individually, and ultimately accept or reject them on the case by case basis, instead of doing all at once.

On that note, I already have plans for additional UI scales and how to better handle the scale extending beyond the available screen resolution. It should be a graceful and a more granular system and we should also handle existing app settings from beta 1 for compatibility. I'll make these changes tomorrow myself.

> Fixed resizing issues after UI scale change.

Can you explain a bit more what the issue is? I know that there is a bug when you restart the program after setting the scale to 2, and it gets much bigger than it should. Is that this bug or something else? Some screenshots or a clip would be nice, since it's a visual issue.

> Changed how menu handled a bit for more save usage - using a TabContainer istead of PanelContainer and individual button signal connections to navigation.

Can you explain why this would be a better way to handle this? To me it seems like an arbitrary change, and button groups are a perfectly fine solution for a group of buttons which can only be toggled one at a time.

> Aded "exit_app()" func to Controller singleton trying to fix harmless crash on app exit (failed). I think it can be good place to make exit preporations in the future.

The unexpected exit/crash at exit is caused by Godot. It's a known bug related to GDExtension and the use of engine singletons, and it will be fixed once I update GDSiON to align with Godot 4.3 beta.

**Comment by RikKargones** [comment]
> Can you explain why this would be a better way to handle this? To me it seems like an arbitrary change, and button groups are a perfectly fine solution for a group of buttons which can only be toggled one at a time.

Just move FullscreenToggle button onto 1-st place, like on screenshot. Menu will start showing wrong tabs or even crash app (out of array error). Just bumped into it when changed it's position upon tests.

изображение

Funcs in Menu.gd uses button index inside parent control. This can't allow free button repositioning if needed.

TabContainer already handles tab showing and will just trow an error in console if you try to show unexciting tab without crashing.

Direct signals bind might look as a clumsy approach, but it grants more control other "what button should lead to what" and excludes unexpected behavior.

> Can you explain a bit more what the issue is? I know that there is a bug when you restart the program after setting the scale to 2, and it gets much bigger than it should. Is that this bug or something else? Some screenshots or a clip would be nice, since it's a visual issue.

Maybe?.. If you're saying about code in Main.gd with HACK comment - it is, but I just utilize it with proper sets of window max_size/min_size. It's also about issue when window becomes bigger then screen after GUI resize. Ah! Also it's about mouse offset inside program.

About what - just tested it and it happens at the same time as this bug (window also always positioning itself over upper screen border). Both affected areas (PalletEditor and Popups) used under CanvasLayer's - menus for instance working as usual.

изображение

I think I was should wrote about this fixes more detailed. Sorry for confusing)

Here screenshots what show GUI scales now (my screen res - 1366:768). It's their minimum window size.

Supersmall (0.5):
изображение

Small (0.75):
изображение

Normal (1.0):
изображение

Big (1.25) Showing what window don't go out of screen borders:
изображение

Anyway, if you're saying you'll will add GUI sizes yourself - well, in any case don't hesitate to look) Maybe you'll find something useful to copy-paste)

**Comment by YuriSizov** [comment]
> This can't allow free button repositioning if needed.

That's totally fine, though. We don't need to create a solution for a general case, only for our specific layout. This may not be scalable, but it doesn't have to be. If the button needs to be moved, then the logic can be fixed to add an offset, and that's it. I understand where you're coming from, but in this case I prefer to focus on the result that end users see rather than on perfect architecture.

Also tabs come with their own complexities if you need to do something more with them, or even style them. It's okay to implement something custom even if there is a similar built-in component, if that unties your hands otherwise.

> I've just extended GUIScalePreset and _gui_scale_factors enums, nothing more

Yes, I know. But that means that an already arbitrary values of 1 and 2 are complemented by more arbitrary values which are also out of order. Imagine if you decide to edit the app config by hand and incrementing the display scale setting makes the UI smaller all of the sudden? While we're in beta, we can make things nicer than that, but then we need to handle values which users who already tried Bosca Ceoil Blue beta 1 may have.

In any case, I think a solution should be to store the actual scale factor, so users can edit it freely if needed, but keep fixed presets on the Advanced tab. And if the current scale factor makes the app size bigger than the screen size, we can reduce the scale factor until it fits (with a reasonable limit). Adding a scroll container is a hacky fix, I'd rather make something nicer and still enforce some lower boundary.

Well, you'll see what I mean soon.

> I think I was should wrote about these fixes more detailed. Sorry for confusing

No worries! Thanks for accepting my feedback <3 I'll work on the fixes that I have planned, and then we can get back to maybe some improvements of yours if any are still relevant by then.

**Comment by YuriSizov** [comment]
Hey, I'm going to close this PR. I've rescaled the app so now it renders at a more appropriate smaller size natively, which means that there should no longer be scaling issues for anyone. If you still can find some issues with the latest commit in `main`, please let me know via a bug report so we can investigate!

Thanks for contributing <3

**Pull request closed without merging**
